
var React = require('react');

var MessageBox = React.createClass({


	getInitialState: function () {
		var initialMsg = this.props.sentIn
	    return {
	        isColorful: true,
	        titleMessage1: initialMsg,
	        titleMessage2: "alternative message is this here",
	        displayedMessage: initialMsg 
  
	    };
	},

	getDefaultProps: function(){
		return {
			sentIn : "i am a default poopypants"
		}
	},



	_changeColor: function(){
		
		if (this.state.isColorful){
			this.setState({
				isColorful: false,
				displayedMessage: this.state.titleMessage2
			})
		} else {
			var otherMsg = 
			this.setState({
				isColorful: true,
				displayedMessage: this.state.titleMessage1
			})
		}
	},

	render: function(){
		var subPropValue = 'hey there im going down to the suuubbbb'

		var inlineStyles = {
			color: this.state.isColorful ? 'pink' : 'chartreuse',
		}

		var propsdemo= "<MessageBox sentIn:{'props passed in'} />"
		console.log(this.props)

		//(1a) note: react/jsx automatially joins an array
		var nodez = [
				'<p>wow</p>',
				'<p>check this</p>',
				'<p>ooouuuutt</p>'
		]

		return (
			<div>
				<h1>Props </h1>
				<h3><code> this.props.sentIn </code>: {this.props.sentIn}</h3>
				<p> <small>props are sent in when the component is initialized
				   like this:  <code> {propsdemo}</code> </small> </p>

				<hr/><hr/>

				<h6>ArrayTest</h6>
				(1b)<br/>
				{nodez}
				<hr/><hr/>
				<h2>Rendered from state: <em> {this.state.displayedMessage} </em> </h2>
				
				<h4>This  <span style={inlineStyles}>cool color here</span> is generated by state </h4>
				<button onClick={this._changeColor} >Change color</button>
	 							
				<p><SubMessage forSub={subPropValue}/></p> 
			</div>
		)
	}

})


	var SubMessage = React.createClass({
		render: function(){
			return(
				<small>{this.props.forSub}</small>

				)
		}

	});


export default MessageBox